[package]
name = "softkvm"
version = "0.1.0"
edition = "2021"
proc-macro = true

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "softkvm-server"
path = "src/server.rs"

[[bin]]
name = "softkvm-client"
path = "src/client.rs"

[dependencies]
ddc-hi = "0.4.1"
tonic = "0.12.2"
prost = "0.13"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build = "0.12"
